class_path: torchmetrics.MetricCollection
init_args:
  metrics: # Use this for: BACE, BBBP, HIV
    f1:
      class_path: torchmetrics.classification.BinaryF1Score
    roc-auc:
      class_path: torchmetrics.classification.BinaryAUROC
