class_path: chebai.models.ElectraAugmented
init_args:
  add_embedding_size: 16
  n_global_properties: 2841
  optimizer_kwargs:
    lr: 1e-3
  config:
    vocab_size: 1400
    max_position_embeddings: 1800
    num_attention_heads: 8
    num_hidden_layers: 6
    type_vocab_size: 1
    hidden_size: 256

