- class_path: chebai.trainer.InnerCVTrainer.ModelCheckpoint
  init_args:
    monitor: val_micro-f1
    mode: 'max'
    filename: 'best_{epoch}_{val_loss:.4f}_{val_micro-f1:.2f}'
    every_n_epochs: 1
    save_top_k: 5
- class_path: chebai.trainer.InnerCVTrainer.ModelCheckpointCVSupport
  init_args:
    filename: 'per_{epoch}_{val_loss:.4f}_{val_micro-f1:.2f}'
    every_n_epochs: 5
    save_top_k: -1