- class_path: chebai.callbacks.model_checkpoint.CustomModelCheckpoint
  init_args:
    monitor: val_micro-f1
    mode: 'max'
    filename: 'best_{epoch:02d}_{val_loss:.4f}_{val_macro-f1:.4f}_{val_micro-f1:.4f}'
    every_n_epochs: 1
    save_top_k: 3
- class_path: chebai.callbacks.model_checkpoint.CustomModelCheckpoint
  init_args:
    filename: 'per_{epoch:02d}_{val_loss:.4f}_{val_macro-f1:.4f}_{val_micro-f1:.4f}'
    every_n_epochs: 25
    save_top_k: -1
- class_path: lightning.pytorch.callbacks.early_stopping.EarlyStopping
  init_args:
    monitor: "val_loss_epoch"
    min_delta: 0.0
    patience: 3
    verbose: False
    mode: "min"
