class_path: chebai.models.ensemble.ChebiEnsemble
init_args:
  model_configs: {
    "model_1_name": {
      "ckpt_path": "path/to/your/model_1/checkpoint.ckpt",
      "class_path": "path/to/your/model_1/class",
      "labels_path": "path/to/your/model_1/classes.json",
    },

    "model_2_name": {
      "ckpt_path": "path/to/your/model_2/checkpoint.ckpt",
      "class_path": "path/to/your/model_2/class",
      "labels_path": "path/to/your/model_2/classes.json",
    },
  }
