name: Unittests

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
          python -m pip install -e .

      - name: Display Python & Installed Packages
        run: |
          python --version
          pip freeze

      - name: Run Unit Tests
        run: python -m unittest discover -s tests/unit -v
        env:
          ACTIONS_STEP_DEBUG: true  # Enable debug logs
          ACTIONS_RUNNER_DEBUG: true # Additional debug logs from Github Actions itself

      # SSH Debugging (Optional)
      # Uncomment this step to open an SSH session into the GitHub Actions runner.
      # This helps debug issues that occur only in CI by allowing manual inspection.
      # Once enabled, GitHub will print an SSH command in the logs, which you can use to connect.
      # To exit the session and continue the workflow, type 'exit' in the terminal.
      #- name: Debug with SSH
      #  uses: mxschmitt/action-tmate@v3
